### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by DontAskDontTell** [mirinsoft/sharpapp#1]
When the apps list is selected as one large remove list (50 items or more), the pop up listing goes off the bottom of the screen so there is NO WAY to select yes or no to complete the task or not, as there is NO SCROLLING in the window, so no way to select anything. The program then has to be forceably shutdown via task manager as it freezes the main window BEHIND this pop up box and stops any further input, the items then need to be re-selected, 10 or less at a time. When any of the included scripts DO run, they remove nothing, as the Powershell window shows ALL the files need futher permissions to allow removal and the list reverts to the same as it was to start with. In other words, it DOES NOT WORK, YET. It requires elevated Powershell permissions that are NOT available to the local administrator account, and there is no included instructions on how to achieve these higher permissions. Faults are due to this being a BETA release I assume. Hopefully it will work one day.

**Comment by Belim** [comment]
Regarding the GUI. Im working here with a > 30 Inch monitor and had no idea it wouldn't all fit in the message box also with a smaller resolution :D I was able to recreate the problem on a 19-inch monitor. I will look into this in a upcoming version

I can't recreate the problem with PowerShell. PimpApp is always running with elevated rights, so also the powershell instance. I have tested this on several machines. We'll see if others have this as well ..

**Comment by DontAskDontTell** [comment]
No problems, I understand it's still an early version. The Powershell issue is more likely MY fault than the APP's, I am not a software creator, and I don't know how to use Powershell at all, IF I ever need to be at root level, I use CMD. It might also be due to the fact the test was in a VM, not on real hardware. The 23 inch monitors I have show about 20 items before the screen lower edge, a simple scrolling bar on the side would fix the issue for any size screen. When the list is open and the OK button is not visible, the window cannot be closed. The close X in the top right corner doesn't seem to work. The window can be moved around by click and drag, but not closed.
Still a greeat bit of work, running the scripts as standalone's seems to let them work. The failures I see in Powershell are for removal of things like Cortana and Edge, but as I said, I do not understand Powershell, I might be completely incorrect my interpretation of what the screen is saying, MOST of the RED error messages flash by far to quickly to read. All I can catch now and then is permission denied warnings and some other lack of correct permissions lines.

**Comment by Belim** [comment]
I don't know what it's like in a vm. I don't need that for SharpApp :P I'm testing on physical hardwareand it runs fine.
Regard the UI bug, please check one of the newer builds.
