### ISSUE TITLE
High DPI Scaling

### ISSUE THREAD

**Issue by coombech** [mirinsoft/sharpapp#10]
Latest version of SharpApp (0.33.0.0) doesn't scale correctly on high DPI monitors (5120x2880). Text is very blurry. Have tried changing "Change high DPI Settings" on the compatibility tab of Sharp.exe properties with no success.

**Comment by Belim** [comment]
:ok_hand: Thanks, will be fixed in next build (maybe tomorrow)

**Comment by coombech** [comment]
Thank you for you your very quick response, time and effort developing this incredibly useful app! I'm a Windows insider and regularly install preview builds which resets the settings and pre installed apps!

**Comment by Belim** [comment]
I'm glad you're enjoying it. 
Should be now fixed in in https://github.com/mirinsoft/sharpapp/releases/tag/0.34.0
Give it a try!

**Comment by coombech** [comment]
Tried 0.34.0 and it now scales correctly. Thank you!
