### ISSUE TITLE
Unhandled exception if hosts file are missing

### ISSUE THREAD

**Issue by lst97** [mirinsoft/sharpapp#11]
Unhandled exception if hosts file are missing under system32 during start up.

![Untitled](https://user-images.githubusercontent.com/16495912/81241384-68999a80-904d-11ea-9464-790d9e327681.png)
_Tested build: 0.33.0 (Achilles)_

**Comment by Belim** [comment]
:clap: A really good one, as i've never seen a system without a hosts file :sweat_smile:
Thanks, will be fixed in upcoming release

**Comment by Belim** [comment]
Fixed here https://github.com/mirinsoft/sharpapp/releases/tag/0.34.0

**Comment by lst97** [comment]
1. My apology, I forgot to mention that the **Add community rules** under telemetry also an unhandled exception if hosts missing.

![InstantGif_2020 05 08-11 50_01](https://user-images.githubusercontent.com/16495912/81362368-0fe90100-9124-11ea-9464-fbdd64a7d772.gif)

2. There are a minor UI display problem I think, the selected field will plain white after pressing another button.

![InstantGif_2020 05 08-11 59_01](https://user-images.githubusercontent.com/16495912/81362460-4757ad80-9124-11ea-8086-58977ab9f85b.gif)

Thank you. 
_Tested build 0.34.0 (Achilles)_

**Comment by Belim** [comment]
1. Ups, missed it too ;) Thanks :ok_hand: will be fixed in the build.
2. Because the control has no focus anymore. This is unfortunately normal behavior with this control. I will play with it some more as the green marked ones are the installed i thought better displaying them as greyed out (with a light forecolor) instead green :confused:

**Comment by lst97** [comment]
> 1. Ups, missed it too ;) Thanks 👌 will be fixed in next build.
> 2. Because the control has no focus anymore. This is unfortunately normal behavior with this control. I will play with it some more as the green marked ones are the installed i thought better displaying them as greyed out (with a light forecolor) instead green 😕

If no focus color able to change to gray, it would be better as it's conflicted with the background color.

**Comment by Belim** [comment]
Fixed here https://github.com/mirinsoft/sharpapp/issues/11 incl. the UI bug

**Comment by lst97** [comment]
I think I am so good at looking for Unhandled exception in missing file. @Belim 
Under setting -> protect host file

![Untitled](https://user-images.githubusercontent.com/16495912/81805005-74112800-955d-11ea-803d-77956eb29c7e.png)
