### ISSUE TITLE
App becomes unresponsive in telemetry tab

### ISSUE THREAD

**Issue by xcasxcursex** [mirinsoft/sharpapp#13]
If I select 'Telemetry' from the side pane, the tab takes a few dozen seconds to load the hosts file, during which time it is unresponsive. Clicking on the 'Add community rules' button, the app becomes entirely unresponsive and I have to end-task it.

I suspect that there is some issue with the app handling my very large hosts file. I use https://github.com/StevenBlack/hosts via https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate, and as a result of blocking all the available options, my hosts file is some 86000+ lines long.

**Comment by Belim** [comment]
I will also see what can be done . The ***Add community rules***  reacts sluggishly here too :open_mouth:

**Comment by Belim** [comment]
This should work better https://github.com/mirinsoft/sharpapp/releases/tag/0.34.1

**Comment by xcasxcursex** [comment]
Much better, thanks! It still becomes temporarily unresponsive while initially loading the hosts file into telemetry tab, but that's not unreasonable given my unreasonably large hosts file ;) ...and it's only a few seconds. Once that's done, the 'Add community rules' dialog loads the list instantly. When I exit that dialog, the tab pauses to re-load the hostsfile, but again, that's not unreasonable, and it comes back to life quickly.

Cheers!
