### ISSUE TITLE
Preinstalled Apps Not Deleted For All Users

### ISSUE THREAD

**Issue by coombech** [mirinsoft/sharpapp#15]
With the latest build 0.34.0, when uninstalling preinstalled apps, they're not uninstalled for all users. For example I run on main user account and have 101 apps still showing as installed after removing the unwanted apps. Then on the second users account the apps uninstalled from the main user account are still installed. However SharpApp doesn't see those apps in the list, so they cannot be selected for uninstallation.

**Comment by Belim** [comment]
SharpApp uses the built-in PowerShell flags to remove preinstalled apps.
Please open an elevated PowerShell instance and enter 

`Get-appxpackage *pattern/name of packge* | remove-appxpackage -AllUsers`

Does this work for you?
