### ISSUE TITLE
What is the purpose?

### ISSUE THREAD

**Issue by demdante** [mirinsoft/sharpapp#17]
To whom this may concern,
I am reaching out to understand what the purpose of this github repo is.  Why create a repo that doesn't house the full project?  Isn't the whole point of Github to share code, collaborate with other developers, and allow them to contribute to a project?  However, this repo only contains the privacy templates.  Thats it.  Does that mean that we are not allowed to contribute?  If so, then why Github?  In the end, its up to you, it just seems like an odd decision.

**Comment by Belim** [comment]
"GitHub provides hosting for software development version control, access control and several collaboration features such as bug tracking, feature requests, task management, and wikis for every project." -Wikipedia

You can contribute in many ways.

**Comment by ilindaniel** [comment]
Exactly my thought. If you publish scripts to the public audience, you might aswell publish the whole application. Otherwise you can't call Debotnet open source and we can't be sure if the program includes backdoors.

Belim doesn't even respond to mails on why he includes third party, non open-source tools in some of his scripts.

**Comment by Belim** [comment]
> Otherwise you can't call Debotnet open source and we can't be sure if the program includes backdoors.
> 
I have never declared the application as open source and talked ONLY about transparency. If then, maybe the media!

> Belim doesn't even respond to mails on why he includes third party, non open-source tools in some of his scripts.

I can't answer 89 mails every day and 64 with the same question. Here at github you would have got one for sure

**Comment by vatterspun** [comment]
I know this topic is closed, but you mentioned over on the debotnet thread 

"I am also not completely closed to the open source idea" https://github.com/mirinsoft/debotnet/issues/54#issuecomment-627935627 ... is there something that would change your mind there?

> I can't answer 89 mails every day and 64 with the same question.

Time to setup an FAQ?
