### ISSUE TITLE
[UI] MessageBox display issue

### ISSUE THREAD

**Issue by lst97** [mirinsoft/sharpapp#19]
I think there's a MessageBoxs' string formatting issue in appPrivacyTemplate && settingsPrivacyTemplate under scripting.

![appPrivacyTemplate](https://user-images.githubusercontent.com/16495912/81768222-ca5e7680-951d-11ea-8260-e6cf2ff61817.png)
![settingsPrivacyTemplate](https://user-images.githubusercontent.com/16495912/81768227-cb8fa380-951d-11ea-9a5c-a82009195009.png)

Tested Build: _0.34.2_

**Comment by Belim** [comment]
Just update your templates (check all templates form dashboard > Install selected templates again) end everything should be fine.
I've change the way the way how information and descriptions are fetched from the PowerShell files and populated into the MessageBox.

**Comment by lst97** [comment]
> Just update your templates (check all templates from dashboard > Install selected templates again) and everything should be fine.
> I've change the way how information and descriptions are fetched from the PowerShell files and populated into the MessageBox.

Confirmed, problem solved.
