### ISSUE TITLE
Suggestion: Add ability to quickly run a revert of the basic template

### ISSUE THREAD

**Issue by rkresha** [mirinsoft/sharpapp#2]
Much like you can do with the Interactive template. Just in case someone changes their mind and they don't wanna manually adjust the basic template back to defaults.

**Comment by Belim** [comment]
This is definitely a good point. I'll see how I can make that happen.
E.g. one could could grab the `basicPrivacyTemplate.PS1` file in scripts folder, flip all values to default and put it back as `undo_basicPrivacyTemaplate.PS1` ... the simplest thing

**Comment by rkresha** [comment]
@Belim Valid point and something I'm comfortable with doing was simply looking at it from a consistency and user experience angle.

**Comment by Belim** [comment]
I'm with you and added another script in 0.24 for reverting changes made with basic privacy template
https://github.com/mirinsoft/sharpapp/releases/tag/0.24.0

**Comment by rkresha** [comment]
Ok cool. Going ahead and closing this out.
