### ISSUE TITLE
Merging different telemetry IP address block lists

### ISSUE THREAD

**Issue by saturnotaku** [mirinsoft/sharpapp#23]
I installed the telemetry IP address block list and now wish to remove it, but selecting either remove or remove all seemingly does nothing, or rather the entry doesn't disappear from the list. This is on version 0.40.1.

**Comment by Belim** [comment]
Cannot confirm this. You cant even remove one entry?
Any error messages?

**Comment by saturnotaku** [comment]
No error messages. Tried on two different computers. Selecting "Remove" or "Remove all" under the "more options" header does nothing.

**Comment by Belim** [comment]
Which rules did you applied? Something must be wrong with your hosts file.
Does "Restore to default" work for you?

**Comment by saturnotaku** [comment]
OK, I'm stupid - I didn't realize that the rules have to be added manually. I thought that's what the privacy templates were for so we're good now, but I did want to ask: Can you only install one set of rules at a time via the app? For example, I select the "extra" rule set, hit apply, and it copies to the hosts file, no problem. Then if I got back to the "add community rules" section and select, say, the "spy" template, it overwrites what was already there. Is this the expected behavior?

**Comment by Belim** [comment]
nobody is stupid. Let's just say that technology is to blame :grin:

Merging different hosts file has already been asked here.
https://github.com/mirinsoft/sharpapp/issues/8
At that time, I was against it, so yes to "expected behavior". Now I think there's room for improvement. I'll keep that in mind

**Comment by saturnotaku** [comment]
Appreciate the understanding. It's easy enough to copy/paste everything into the hosts file myself. For what my opinion is worth, merging files together is not something that should be high on the priority list right now. I'll go ahead and close this thread.
