### ISSUE TITLE
Minor UI issue with check all button under policies

### ISSUE THREAD

**Issue by lst97** [mirinsoft/sharpapp#24]
I think there're a minor issue with the check all button, I clicked check all then I click to other category, the check all button state did't reset, therefore I have to click 2 times for the check all button. Thank you.

![InstantGif_2020 05 25-14 56_01](https://user-images.githubusercontent.com/16495912/82779822-89a91a80-9e98-11ea-8c63-bc74ed4b68d5.gif)

Tested Build: _SharpApp 0.42.1 (Helios)_

**Comment by Belim** [comment]
Should be fixed here
https://github.com/mirinsoft/sharpapp/releases/tag/0.43.0

The checkbox state gets "empty" after switching the category.

**Comment by lst97** [comment]
Confirmed.
