### ISSUE TITLE
Merge Cleanmgr+ with SharpApp [Suggestion] [Feature Request]

### ISSUE THREAD

**Issue by AvinashDwivedi-Indian** [mirinsoft/sharpapp#25]
Since both applications work to make windows 10 better, why don't you merge them?
Also both are super light-weight so, there's no harm (to size) in doing this.
Anyways, these applications are the best in market even paid applications aren't this simple, lightweight and provide much functionality.
Also I have another request: Please keep them free!😂

**Comment by Belim** [comment]
If I did it for the money, I'd be broke long ago 😂

These two would fit better together  :smile:, but unfortunately not in terms of licensing.  
![SharpApp_fs9EMhTfrP](https://user-images.githubusercontent.com/57478606/83000626-e3c9ed00-a00a-11ea-9320-7cbb54b051ae.png)
The left side is https://github.com/mirinsoft/burnbytes

but that's not gonna happen. I hate bloated apps

**Comment by AvinashDwivedi-Indian** [comment]
Ok!
No Problem.😇
Anyways love your work.🥰

**Comment by Belim** [comment]
I should hope so :relaxed:
I'm considering including Burnbytes as an option, a sort of add-on
