### ISSUE TITLE
Revert Changes Option

### ISSUE THREAD

**Issue by jenabaivab** [mirinsoft/sharpapp#27]
I had run the professional template a few weeks back, and everything was fine. For the past week or so, there are have been a lot of issues regarding windows update. My hard drive copy and cut speed has been reduced to kilobytes.
Is there any way to revert the changes that were implemented by the script without just reinstalling the entire operating system?

**Comment by Belim** [comment]
The pro template includes six third-party script files from
https://github.com/W4RH4WK/Debloat-Windows-10

Reverting is not possible,but you will find on the original repo a list of well known issues. Maybe it could help.
