### ISSUE TITLE
version 0.32.1 - disable-windows-defender script error

### ISSUE THREAD

**Issue by ombrisban** [mirinsoft/sharpapp#7]
Hi,
this script does not work correctly in x86 version of Windows. The Group Policy registry key specified exist only in x64 versions:

> HKLM:\SOFTWARE\Wow6432Node\Policies

In x86 versions the correct key is:

> HKLM:\SOFTWARE\Policies

**Comment by Belim** [comment]
Hi,
the Wow6432Node is a compatibility path for 32bit programs under 64bit, so that they work smoothly.
In some places in the Registry Windows automatically synchronizes the 64- and 32-bit branches. For example, when you set policies in SOFTWARE\Polices , Windows immediately copies them to the other branch to SOFTWARE\Wow6432Node\Policies 

Its not always the case but i think this one should also work correctly on 32-bit systems. Did you run it and check for synchronization of the keys?

More infos here https://docs.microsoft.com/en-us/windows/win32/sysinfo/32-bit-and-64-bit-application-data-in-the-registry

**Comment by ombrisban** [comment]
Hi,
as you say, the Wow6432Node is a compatibility path for 32bit programs that run under 64bit version of Windows. But I'm running a 32bit version (x86) of Windows 10 Pro. In 32bit version of Windows, Wow6432Node does not exist.

I have run the script once and rebooted. I have run the script again and rebooted. I have repeated this process twice.

Then I have checked the result:
- All tasks specified in the script are disabled (OK)
- Registry keys related to Group Policies does not exists (wrong)
- _Sense_ service is stopped and configured as disabled (OK)
- _WinDefend_ service is started and configured as automatic (wrong)
- _WdNisSvc_ service is started and configured as manual (wrong)
- Windows Defender context menu item seems to be removed (OK)
- Windows Defender GUI seems to be removed (OK)

Windows Defender taskbar icon says: "Windows Security - No action required"

I will try to modify the script so that it works in the 32bit version. If i succeed i will put the result here.

Regards,

**Comment by ombrisban** [comment]
Hi,
regarding the problem with the registry key, the correct thing is to use:

> HKLM:\SOFTWARE\Policies

On 32bit Windows Systems only this key exists. And on 64bit Windows Systems, when you add or delete information in this key, the system itself automatically performs the same operation in  the Wow6432Node key

**Comment by ombrisban** [comment]
But there are other problems. **SharApp** does not seem to load `force-mkdir.psm1` and `take-own.psm1` modules (possibly because they do not exist in the corresponding directory). I have downloaded the modules manually and run the script in a PowerShell console. And this is the output:

![screenshot-38](https://user-images.githubusercontent.com/64747841/81226202-bf21bd00-8fea-11ea-8140-36221d8a1f07.jpg)


Therefore the `force-mkdir.psm1` module works correctly and **SharApp** fails to load it. But the `take-own.psm1` module has some problem and it doesn't work properly (there is a note at the beginning of the module that says there is a problem with the "Takeown-Registry" function).

I hope this help you solve de problem

Regards

**Comment by Belim** [comment]
The author of this script file has confirmed this
https://github.com/W4RH4WK/Debloat-Windows-10/issues/121

So in summary, it didn't work for you? Which Windows version are you using? Its not compatible with the LTSB

**Comment by ombrisban** [comment]
i'm using Windows 10 Pro 1909 in both versions 32bit and 64bit

**Comment by Belim** [comment]
This script is provided by third parties https://github.com/W4RH4WK/Debloat-Windows-10/issues/121
I'm waiting for the upcoming version 2004 and see if the original author can make it work again, otherwise I will remove it from SharpApp.
