### ISSUE TITLE
[v0.32.0] Telemetry Questions

### ISSUE THREAD

**Issue by goodboi69** [mirinsoft/sharpapp#8]
1) Could a description be added for what each of the community rules do?
2) Can you combine rules? What would be the benefits or issues by doing that?
3) Adding any community rules overrides any, already, added lines in the host file. Can the app just add any community rules to the already existing one?

**Comment by Belim** [comment]
1. Version 0.34 now tells a little more about the hosts files
https://github.com/mirinsoft/sharpapp/releases/tag/0.34.0

2+3 Yes, but i will not recommend merging the provided hosts file. Please read the new explanations then you will understand. The "extra" and "update" hosts are dangerous for the normal user
